### ISSUE TITLE
Simulate Session event on OSX

### ISSUE THREAD

**Issue by MarcAntoine-Arnaud** [Narsil/rdev#46]
Hi !

I'm currently using grab (unstable) with simulate because I need to detect double clic.
And I got an issue with that because the simulate is on HID, so it re-throw the same event in the grab ... and loop !
I have tested to change locally to Session here: https://github.com/Narsil/rdev/blob/master/src/macos/simulate.rs#L92
And it works perfectly. Do you have any reason to send an event on HID and not on Session layer ?

Thank you !

**Comment by Narsil** [comment]
I think what really matters here is to have a consistent behaviour across OSs (which is probably not the case atm). Receiving simulated events in listen or grab is actually quite sensible, since you want your simulated events to be received by other programs which might listen too. I'll admit it's debatable.

In your case, can't you workaround, by setting a flags somewhere to behave differently if it's your event that's flowing or not ?
Also if you send the same event that you listened to (which I guess is the problem since you have a loop), you probably just let it flow, no ? (Maybe in the case of clicks you are changing the coordinates, then you probably use that information to differentiate ?

**Comment by MarcAntoine-Arnaud** [comment]
In my case is with keyboard, for double clic actions - not for mouse.
It's for specific use cases with eye-impaired keyboard improvement application.

And in this case it's impossible to detect if it's the re-throw of the previous event or a second event provided by human ...
So maybe to prevent it can make sense to simulate to session level, and provide function to edit event properties...

Maybe to have something more configurable it can be interesting to:
1. Create a trait to define `simulate` action
2. Create structs for each platform
3. implement Simulate trait for each platform struct
4. add specific functions to configure events into the implementation of the struct (for example here to change the custom OSX output event layout).

**Comment by Narsil** [comment]
Oh you mean you are transforming a single click into a double click ?

Then keeping the time around of the last click should help no ? I know these are quick&dirty solutions, but really if you want full control over what you do, you probably should fork this (and PR if you want).

 My intent here is not to have fully customizable tool, but to have a simple one, with common API across OSs. I understand that struct and traits are more flexible, than simple fuctions, but functions are simpler to reason about. In my view simplicity  is really important, so the current API probably won't change. Finally, enabling customization based on OS I think would defeat the purpose of a cross OS library.

**Comment by Narsil** [comment]
Did you figure out a solution ? 

Can I close this issue if that's the case ?

**Comment by MarcAntoine-Arnaud** [comment]
Thanks with the unstable grab it works for me !
Thank you
