### ISSUE TITLE
Can I send <ctrl+c> to copy something to the system clipboard

### ISSUE THREAD

**Issue by sincerefly** [Narsil/rdev#50]
I try use this code to copy when selected some text:

```
send(&EventType::KeyPress(Key::ControlLeft));
send(&EventType::KeyPress(Key::KeyC));
send(&EventType::KeyRelease(Key::KeyC));
send(&EventType::KeyRelease(Key::ControlLeft));
```

seem doesn't work.

**Comment by Narsil** [comment]
Try to add some sleep commands between sending events. OS seem to need that in order to acknowledge keypresses. (10ms seems to be enough try longer to make sure.). 
If you just need copy, try putting one just between keypresses and keyreleases., If that fails put them everywhere.
If that does not work, maybe your selection is empty and so nothing happens ?

**Comment by sincerefly** [comment]
Thanks for you reply, Add time wait between Press-Control and Press-KeyC Fixed my problem.
