### ISSUE TITLE
allow `listen` to take a closure

### ISSUE THREAD

**Issue by elkowar** [Narsil/rdev#60]
The `rdev::listen` function currently takes a function pointer, which strongly limits how easily it can be integrated into any kind of application structure. Instead, it should be possible to make it work with a proper `FnMut` (/`Fn`) closure.

**Comment by Narsil** [comment]
Feel free to try. I would happily merge something that is working and not making too many assumptions.

Underlying OS APIs are not that nice, for instance X11 explicitly wants a function pointer.
Enabling `FnMut`/`Fn` would require quite a bit of work from my understanding (to isolate those raw pointer function calls), which in addition might not even be useful for all purposes. That's why it's not already in there.
But I might be mistaken.

**Comment by elkowar** [comment]
I asked about the function-pointer vs. closure issue in the rust community discord, and got the following response:
> You can fully support closures at least on linux https://www.x.org/docs/Xext/recordlib.pdf
> XRecordEnableContext takes a closure date argument
> Ofc you'll want to check the other platforms too
> winit uses the same APIs and supports closures
> windows also has context parameters

> And MacOS has refcon https://developer.apple.com/documentation/coregraphics/1454426-cgeventtapcreate so yea @ElKowar don't use some ThreadLocal hack :grin:

Seeing this, it should be possible! I'd maybe try myself at a PR, but i have neither a Mac setup available nor a functional Windows environment to easily test the windows part on,....
